###############################################################################
###   CONTACTS
###############################################################################

### CREATE A NEW CONTACT
POST http://localhost:5000/api/contacts
Content-Type: application/json

{
  "company": "Apple Computer",
  "street1": "2234 Main Street",
  "street2": "Unit 1234",
  "city": "New York",
  "state": "NY",
  "zip": "10101",
  "email": "fred@jones.com"
}



### GET ALL CONTACTS
GET http://localhost:5000/api/contacts



### GET A CONTACT BY ID
GET http://localhost:5000/api/contacts/600c9b5ef96c0c4720c85c1c



### UPDATE/PATCH A CONTACT BY ID
PATCH http://localhost:5000/api/contacts/600f4d19953f7861840cde35
Content-Type: application/json

{
  "name":{
    "last": "Jones",
    "first": "Sam"
  },
  "company": "ABC Corp",
  "street1": "2235 Main Street",
  "street2": "Unit 1238",
  "city": "New York",
  "state": "NY",
  "zip": "10101",
  "email": "fred@jones.com"
}



### DELETE A CONTACT BY ID
DELETE http://localhost:5000/api/contacts/600ca07ea7d3c5235c9e2a43


