### Get root ('/') (Will respond with 'ok')
GET http://localhost:5000/
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDg4ZmQyODA3NmFhMDc0MGUwNWNmYyIsImlhdCI6MTYxMTE3Mzg0MiwiZXhwIjoxNjExMTc3NDQyfQ.B2rwXbERE-4aH3tfTRmp1tK0kF1yV_uElXSK8IhCpmM

###############################################################################
###   USERS
###############################################################################

### REGISTER A NEW USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Dawn",
  "email": "dawn@ianuzzi.us",
  "password": "lindsay123" 
}



### LOG IN A USER (RETURN A JWT)
POST http://localhost:5000/api/auth
Content-Type: application/json

{
  "email": "art@ianuzzi.us",
  "password": "password123"  
}
 


### GET THE USER INFO FROM THE CURRENT TOKEN
POST http://localhost:5000/api/auth/user
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDRhYjc1YmE5NDY5NGMxMGZmYzBkZiIsImlhdCI6MTYxMTE4MDE1OSwiZXhwIjoxNjExMTgzNzU5fQ.Bbb_17HOdtOGNGUGBybxOLUuzMgbfvtw3hbA6i1a2I4"

}




### Get flat JSON test data
GET http://localhost:5000/api/test



### GET all testdata from MongoDB
GET http://localhost:5000/api/testdata